services:
  database:
    container_name: postgres-betest
    image: postgres:16.3
    restart: always
    ports:
      - ${DATABASE_PORT}
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-data:${DATABASE_DATA}
    networks:
      - fullstack-project
networks:
  fullstack-project:
    driver: bridge
volumes:
  postgres-data:
