import { WeatherApiResponse } from '../models/weather.model';

export const WEATHER_RESPONSE_MOCK: WeatherApiResponse = {
  location: {
    name: 'Agra',
    region: 'Uttar Pradesh',
    country: 'India',
    lat: 27.18,
    lon: 78.04,
    tz_id: 'Asia/Kolkata',
    localtime_epoch: 1720475967,
    localtime: '2024-07-09 3:29',
  },
  current: {
    last_updated_epoch: 1720475100,
    last_updated: '2024-07-09 03:15',
    temp_c: 28.6,
    temp_f: 83.4,
    is_day: 0,
    condition: {
      text: 'Patchy rain nearby',
      icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
      code: 1063,
    },
    wind_mph: 7.2,
    wind_kph: 11.5,
    wind_degree: 61,
    wind_dir: 'ENE',
    pressure_mb: 1001,
    pressure_in: 29.55,
    precip_mm: 1.78,
    precip_in: 0.07,
    humidity: 79,
    cloud: 76,
    feelslike_c: 33.4,
    feelslike_f: 92.1,
    windchill_c: 28.6,
    windchill_f: 83.4,
    heatindex_c: 33.4,
    heatindex_f: 92.1,
    dewpoint_c: 24.6,
    dewpoint_f: 76.2,
    vis_km: 9,
    vis_miles: 5,
    uv: 1,
    gust_mph: 11.4,
    gust_kph: 18.3,
  },
  forecast: {
    forecastday: [
      {
        date: '2024-07-09',
        date_epoch: 1720483200,
        day: {
          maxtemp_c: 35.4,
          maxtemp_f: 95.7,
          mintemp_c: 28,
          mintemp_f: 82.5,
          avgtemp_c: 32,
          avgtemp_f: 89.5,
          maxwind_mph: 8.7,
          maxwind_kph: 14,
          totalprecip_mm: 10.55,
          totalprecip_in: 0.42,
          totalsnow_cm: 0,
          avgvis_km: 9.7,
          avgvis_miles: 6,
          avghumidity: 64,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 89,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Moderate rain',
            icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
            code: 1189,
          },
          uv: 9,
        },
        astro: {
          sunrise: '05:31 AM',
          sunset: '07:16 PM',
          moonrise: '08:25 AM',
          moonset: '09:52 PM',
          moon_phase: 'Waxing Crescent',
          moon_illumination: 9,
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1720463400,
            time: '2024-07-09 00:00',
            temp_c: 30.7,
            temp_f: 87.3,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 81,
            wind_dir: 'E',
            pressure_mb: 1001,
            pressure_in: 29.55,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 71,
            cloud: 23,
            feelslike_c: 36.9,
            feelslike_f: 98.4,
            windchill_c: 30.7,
            windchill_f: 87.3,
            heatindex_c: 36.9,
            heatindex_f: 98.4,
            dewpoint_c: 24.8,
            dewpoint_f: 76.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9,
            gust_kph: 14.5,
            uv: 1,
          },
        ],
      },
    ],
  },
};
